### ISSUE TITLE
bandits tpose on linux server when client connects for 2.15 and 2.16

### ISSUE THREAD

**Issue by cidolfas2021** [vis2k/uMMORPG_CE#23] opened 2020-07-30 13:05 UTC
just what it says.  I build a fresh copy and try to load it to my linux server from namecheap.com and the bandits are in tpose.

**Comment by jonmalave** [comment] 2020-08-03 19:23
> just what it says. I build a fresh copy and try to load it to my linux server from namecheap.com and the bandits are in tpose.

@cidolfas2021 this issue has been around for over 2 years... I reported it before and it has been totally ignored by @vis2k! 

Check the 1 Star Reviews: https://assetstore.unity.com/packages/templates/systems/ummorpg-components-edition-159401#reviews and look for **Spartikus3** review. 

he reported the following 2 years ago: 
- Desynchronization issues in a production environment continue to happen causing players to lose animation synchronization with the server. Causes animated game objects to stand in a T pose and slide around instead of properly animating. Reported multiple times and told I was whining.

I have also reported this issue in Discord Community Chat, and have been banned by @vis2k because he can't handle the truth about his shitty support. 

He cashes in on his many assets, and doesn't properly support them.  

I purchased uMMORPG CE to give it a spin, thinking that it might actually be in a better state but nope same crap!

**Comment by jonmalave** [comment] 2020-08-03 19:37
@vis2k when are you ever going to fucking fix this???? it's been 2 years seriously....  you responded to my 1 Star Review stating i'm a very angry person for years. GET A FUCKING CLUE... look at the crap shit support you provide to your customers.  Here you have @cidolfas2021 reporting an issue that has been reported by myself and probably others for 2 years, and yet it still is a problem out the box with the original uMMORPG and now uMMORPG CE edition. Seriously???  

YES, I totally understand that we are saving so much time by buying uMMORPG... but it is misleading to sell a product that does not work out the box the way it should in the Demo!! 

How can you sell something that looks good in an offline WebGL Demo, but yet totally turns to shit once people try to test it in production with your vanilla template??? 

You have always asked "Does the issue you report happen with the uMMORPG default scene and settings without modifications" YES YES YES... I have tested this shit over and over, reported issues and still totally ignored to this day...  

Truly unbelievable... 

I want to see you walk into a Store, purchase a Lawn Mower... Test it out on your font lawn, then find out it doesn't cut the grass the way you expected it too. Is the Store owner going to tell you, "Stop fucking whining we built a Lawn Mower for you, if it doesn't cut the grass exactly the way you expected it... then go dive into the engine and fix it up" 

No they are not, they are going to replace or fix the fucking Lawn Mower so it cuts grass the way you expect it to work out the box.

What part of this don't you get?  

I'm sure you are a customer of some other business, and when you spend your hard earn cash on something, you expect it to work as advertised! Plain an Simple! If something is advertised to work a certain way, then it should work exactly that way... 

Why do you treat me, and treat other customers like trash, when we are the ones helping you pay your monthly bills by buying your products? 

I have never asked you to add features... I have always simply asked you to fix something that has been broken out the box! And yet i've been totally ignored for years... I've support you by spending my hard earned cash on it and coming back to give it another try again and again... so why can't you simply respond with an estimated time to fix a problem that is not working out the box!? 

Call me a troll, call me angry, call me whatever you want... but you are the one with horrible business practice and support. I'm sure you don't expect to be treated like this as a customer of whatever businesses and products you support, so why do you treat some of us this way? Makes absolutely no sense... 

Your Offline WebGL Demo: https://ummorpg.net/webglCE/ Works Flawlessly... that is exactly what we expect to experience when we host uMMORPG on our own Linux Servers. But yet it doesn't work the same as the Demo. THIS IS FALSE ADVERTISING 

If you are going to argue that it's not false adverting... then fix your fucking asset to work out the box the way you advertise it. SIMPLE!!!!

**Comment by jonmalave** [comment] 2020-08-04 16:32
@cidolfas2021 take note as @vis2k closes my issue being reported in regards to this issue above... i'm asking for him to host a linux server and webgl demo build to prove to us that his asset is working as he says it does according to his Offline WebGL Demo. It does not... watch as he ignores you and ignore me, and does nothing but close these issues without resolving anything. I'll wait for the fuckery that is @vis2k , not even sure how this guy sleeps at night. Hopefully his girlfriend broke up with him already, because surely someone who operates business like this must be a very lonely man. How one handles business relationships are often not too different in how they handle personal relationships. 

Trust me @vis2k i'm far from the angry, unhappy one here... fix your asset! and maybe one day i'll stop reporting how shitting your support is for it and you falsely advertise your product working out the box... I have PROVEN it easily in my Asset Store Review and here: https://github.com/vis2k/uMMORPG_CE/issues/25 but surely you will try to close this and erase my text so no one sees it... 

If anyone reading this finds the above issue closed, and text erased again just take a look at my 1 star asset store review for the details on the con artist that is @vis2k 
https://assetstore.unity.com/packages/templates/systems/ummorpg-components-edition-159401#reviews

**Comment by miwarnec** [comment] 2020-08-28 13:54
@cidolfas2021 please include step by step guide on how to reproduce.
the stress tests always run on ubuntu linux x64 (google cloud), with no synchronization issues.
ideally include a video and reopen the issue, thx

**Closed as completed by miwarnec** 2020-08-28 13:54 UTC
