### ISSUE TITLE
List of Issues

### ISSUE THREAD

**Issue by NataIynn** [vis2k/uMMORPG_CE#30] opened 2020-09-29 13:27 UTC
**1.** While in Server & Play, If you click the 'enter player name box aka typing using the GM Panel, everyone connected to you will start constantly rubberbanding, with the message "Name Single Move, Rejected and Force Reset".
**2:** If you run a server only or server & play through Unity, you cannot connect to your own server using your ISP IP Address. It'll just be stuck at "Connecting...". It works fine if you build your server or game client and do it that way. Just in editor breaks this.
**3.** The game client gets picked up as a false virus for some odd reason on certain computers. It could be the new DLLs, added.
**4.** Some Computers get DLLNotFound Libuv on game build clients, making it 100% impossible to connect to any server. Screenshot posted in #help section.

**Comment by miwarnec** [comment] 2020-09-29 13:59
> **1.** While in Server & Play, If you click the 'enter player name box aka typing using the GM Panel, everyone connected to you will start constantly rubberbanding, with the message "Name Single Move, Rejected and Force Reset".

just checked. is there an easy way to reproduce it with fresh ummorpg from asset store?
I also checked the UIGameMasterTool code. there aren't really any calculations happening until you press the button:
![2020-09-29_15-57-55](https://user-images.githubusercontent.com/16416509/94568254-8cfc4a80-026c-11eb-8718-8a8b295fa001.png)

> If you run a server only or server & play through Unity, you cannot connect to your own server using your ISP IP Address. It'll just be stuck at "Connecting...". It works fine if you build your server or game client and do it that way. Just in editor breaks this.

any easy way to reproduce? I assume you want to connect to your public IP? that generally isn't expected to work unless you opened a port. so it's more weird that it does work in Editor actually

> The game client gets picked up as a false virus for some odd reason on certain computers. It could be the new DLLs, added.

which antivirus tool? this would be really unfortunate since it's a fresh libuv build and they don't provide pre-built dlls. I don't we have a way around it except maybe a warning message that AV might flag it accidentally.

> 4. Some Computers get DLLNotFound Libuv on game build clients, making it 100% impossible to connect to any server. Screenshot posted in #help section.

is this related to 3.? if AV detects it and quarantines it, then the dll would not be found?

**Comment by NataIynn** [comment] 2020-09-30 16:21
> just checked. is there an easy way to reproduce it with fresh ummorpg from asset store?
I also checked the UIGameMasterTool code. there aren't really any calculations happening until you press the button:
- I have did a Game client build in 2019.4.11f, and then just did server & play on the build. As soon as you type anything in the player input field, everyone will rubberband with force resets. I've used the latest build off gitlab as of yesterday. This happens when you're the server host and accessing gm panel.

> any easy way to reproduce? I assume you want to connect to your public IP? that generally isn't expected to work unless you opened a port. so it's more weird that it does work in Editor actually
- It works 100% fine on game builds, but not in unity. It's little odd to me as well.

> which antivirus tool? this would be really unfortunate since it's a fresh libuv build and they don't provide pre-built dlls. I don't we have a way around it except maybe a warning message that AV might flag it accidentally.
- Microsoft Anti-Virus, It didn't really delete any of the files. It pretty much just prevents from being executed. The threat claims as low security.

> is this related to 3.? if AV detects it and quarantines it, then the dll would not be found?
- I'm not sure on that. It's possible. However I've disabled the anti virus and the DLLNotfound still occured.

**Comment by miwarnec** [comment] 2020-10-03 19:31
libuv fixed in next version

**Comment by delgelato** [comment] 2020-10-31 13:15
Halo

The move rejected when server(host) is on an active UI is a bug on the movement side, not on the GM panel side

In PCCM.FixedUpdate, where there's if (!isServer || IsValidMove(move)) (on both combine or non combine move packet handling)
IsValidMove contains a player.IsMovementAllowed, which contains !UIUtils.AnyInputActive()
This shouldn't be used for server side valid move check..


edit:
Solution is, instead of just !UIUtils.AnyInputActive(),
make it (!isLocalPlayer || !UIUtils.AnyInputActive())

**Comment by miwarnec** [comment] 2020-11-07 10:07
checking

**Comment by miwarnec** [comment] 2020-11-07 10:15
> Halo
> 
> The move rejected when server(host) is on an active UI is a bug on the movement side, not on the GM panel side
> 
> In PCCM.FixedUpdate, where there's if (!isServer || IsValidMove(move)) (on both combine or non combine move packet handling)
> IsValidMove contains a player.IsMovementAllowed, which contains !UIUtils.AnyInputActive()
> This shouldn't be used for server side valid move check..
> 
> edit:
> Solution is, instead of just !UIUtils.AnyInputActive(),
> make it (!isLocalPlayer || !UIUtils.AnyInputActive())

great find, thanks so much. this was a very important fix and will be in next version!

**Closed as completed by miwarnec** 2020-11-07 10:15 UTC
